import '../models/restaurant_model.dart';

final List<RestaurantCardData> mockRestaurants = [
  RestaurantCardData(
    id: '1',
    name: 'บ้านสวนผัดไทย',
    cuisine: 'ไทย',
    priceRange: 2,
    rating: 4.5,
    distance: 0.8,
    imageUrl: 'assets/images/res/r1/2.jpg',
    address: '123 ถนนสุขุมวิท แขวงคลองเตย กรุงเทพฯ',
    phone: '0212345678',
    openingHours: '10:00 - 22:00',
    description: 'ร้านอาหารไทยต้นตำรับ เมนูแนะนำ ผัดไทย',
    menuItems: [
      MenuItem(name: 'ผัดไทยกุ้งสด', price: '150 THB'),
      MenuItem(name: 'ผัดไทยไข่เค็ม', price: '80 THB'),
      MenuItem(name: 'ผัดไทยกุ้งกรอบ', price: '60 THB'),
      MenuItem(name: 'ผัดไทยวุ้นเส้น', price: '70 THB'),
      MenuItem(name: 'ผัดไทยทรงเครื่อง', price: '130 THB'),
      MenuItem(name: 'ผัดไทยไข่เค็ม', price: '90 THB'),
    ],
    galleryImages: [
      'assets/images/res/r1/1_1.jpg',
      'assets/images/res/r1/1_2.jpg',
      'assets/images/res/r1/1_3.jpg',
      'assets/images/res/r1/1_1.jpg',
    ],
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '2',
    name: 'ครัวคุณยาย',
    cuisine: 'ไทย',
    priceRange: 1,
    rating: 4.3,
    distance: 1.2,
    imageUrl: 'assets/images/res/r2.jpg',
    address: '456 ถนนพระราม 4 แขวงคลองเตย กรุงเทพฯ',
    phone: '0223456789',
    openingHours: '09:00 - 21:00',
    description: 'อาหารไทยรสชาติต้นตำรับ บรรยากาศอบอุ่น',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '3',
    name: 'Sushi Masa',
    cuisine: 'ญี่ปุ่น',
    priceRange: 3,
    rating: 4.8,
    distance: 2.1,
    imageUrl: 'assets/images/res/r3.jpg',
    address: '789 ถนนสีลม แขวงสีลม กรุงเทพฯ',
    phone: '0234567890',
    openingHours: '11:30 - 23:00',
    description: 'ร้านซูชิพรีเมียม วัตถุดิบสดใหม่จากญี่ปุ่น',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '4',
    name: 'Tokyo Ramen House',
    cuisine: 'ญี่ปุ่น',
    priceRange: 2,
    rating: 4.4,
    distance: 1.5,
    imageUrl: 'assets/images/res/r4.jpg',
    address: '321 ถนนสาทร แขวงสาทร กรุงเทพฯ',
    phone: '0245678901',
    openingHours: '11:00 - 22:00',
    description: 'ราเมนสไตล์โตเกียว น้ำซุปเข้มข้น',
    status: SwipeStatus.pass,
  ),
  RestaurantCardData(
    id: '5',
    name: 'Bella Italia',
    cuisine: 'อิตาเลียน',
    priceRange: 3,
    rating: 4.6,
    distance: 2.8,
    imageUrl: 'assets/images/res/r5.jpg',
    address: '654 ถนนวิทยุ แขวงลุมพินี กรุงเทพฯ',
    phone: '0256789012',
    openingHours: '12:00 - 23:00',
    description: 'ร้านอาหารอิตาเลียนต้นตำรับ พาสต้าทำสด',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '6',
    name: 'Pizza Roma',
    cuisine: 'อิตาเลียน',
    priceRange: 2,
    rating: 4.2,
    distance: 1.8,
    imageUrl: 'assets/images/res/r6.jpg',
    address: '987 ถนนพระราม 9 แขวงห้วยขวาง กรุงเทพฯ',
    phone: '0267890123',
    openingHours: '11:00 - 22:30',
    description: 'พิซซ่าเตาอิฐ สไตล์โรมัน',
    status: SwipeStatus.pass,
  ),
  RestaurantCardData(
    id: '7',
    name: 'Seoul BBQ',
    cuisine: 'เกาหลี',
    priceRange: 2,
    rating: 4.5,
    distance: 1.3,
    imageUrl: 'assets/images/res/r7.jpg',
    address: '147 ถนนเพชรบุรี แขวงมักกะสัน กรุงเทพฯ',
    phone: '0278901234',
    openingHours: '11:30 - 23:30',
    description: 'บาร์บีคิวเกาหลี เนื้อคุณภาพพรีเมียม',
    status: SwipeStatus.pass,
  ),
  RestaurantCardData(
    id: '8',
    name: 'Kimchi House',
    cuisine: 'เกาหลี',
    priceRange: 1,
    rating: 4.1,
    distance: 0.9,
    imageUrl: 'assets/images/res/r8.jpg',
    address: '258 ถนนรัชดาภิเษก แขวงดินแดง กรุงเทพฯ',
    phone: '0289012345',
    openingHours: '10:00 - 22:00',
    description: 'อาหารเกาหลีราคาประหยัด รสชาติต้นตำรับ',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '9',
    name: 'Taco Fiesta',
    cuisine: 'เม็กซิกัน',
    priceRange: 2,
    rating: 4.3,
    distance: 2.3,
    imageUrl: 'assets/images/res/r9.jpg',
    address: '369 ถนนทองหล่อ แขวงคลองตัน กรุงเทพฯ',
    phone: '0290123456',
    openingHours: '11:00 - 23:00',
    description: 'ทาโก้และบูริโต้สไตล์เม็กซิกัน',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '10',
    name: 'El Mariachi',
    cuisine: 'เม็กซิกัน',
    priceRange: 2,
    rating: 4.4,
    distance: 1.7,
    imageUrl: 'assets/images/res/r10.jpg.jpg',
    address: '741 ถนนเอกมัย แขวงคลองตันเหนือ กรุงเทพฯ',
    phone: '0201234567',
    openingHours: '12:00 - 00:00',
    description: 'อาหารเม็กซิกันรสจัดจ้าน บรรยากาศสนุกสนาน',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '11',
    name: 'Dim Sum Palace',
    cuisine: 'จีน',
    priceRange: 2,
    rating: 4.6,
    distance: 1.4,
    imageUrl: 'assets/images/restaurants/chinese1.jpg',
    address: '852 ถนนเยาวราช แขวงสัมพันธวงศ์ กรุงเทพฯ',
    phone: '0212345679',
    openingHours: '07:00 - 15:00',
    description: 'ติ่มซำฮ่องกง ขนมจีบสดใหม่ทุกวัน',
    status: SwipeStatus.yum,
  ),
  RestaurantCardData(
    id: '12',
    name: 'Golden Dragon',
    cuisine: 'จีน',
    priceRange: 3,
    rating: 4.7,
    distance: 2.5,
    imageUrl: 'assets/images/restaurants/chinese2.jpg',
    address: '963 ถนนเจริญกรุง แขวงบางรัก กรุงเทพฯ',
    phone: '0223456780',
    openingHours: '11:00 - 22:00',
    description: 'ร้านอาหารจีนกวางตุ้ง เป็ดปักกิ่งสูตรต้นตำรับ',
    status: SwipeStatus.pass,
  ),
];
