// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAImtyg3la371RZM26irYPETtuDygFX1Q0',
    appId: '1:611474656292:web:b496408e48aba48af25cb1',
    messagingSenderId: '611474656292',
    projectId: 'dishcovery-app-62ab5',
    authDomain: 'dishcovery-app-62ab5.firebaseapp.com',
    databaseURL: 'https://dishcovery-app-62ab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dishcovery-app-62ab5.firebasestorage.app',
    measurementId: 'G-JRTGVW3EZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBc5hjsUa_96Ozrr8BTpmG51s4xASd710',
    appId: '1:611474656292:android:8f86dc26bf1eefccf25cb1',
    messagingSenderId: '611474656292',
    projectId: 'dishcovery-app-62ab5',
    databaseURL: 'https://dishcovery-app-62ab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dishcovery-app-62ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp01cFaEBMv4SmRaTWDoSEWD7U948nfV4',
    appId: '1:611474656292:ios:b22bcf8f5cfa6d38f25cb1',
    messagingSenderId: '611474656292',
    projectId: 'dishcovery-app-62ab5',
    databaseURL: 'https://dishcovery-app-62ab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dishcovery-app-62ab5.firebasestorage.app',
    iosClientId: '611474656292-0mrd908gq6o13pq0fd6ul49uu4g2hh3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishcoveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp01cFaEBMv4SmRaTWDoSEWD7U948nfV4',
    appId: '1:611474656292:ios:b22bcf8f5cfa6d38f25cb1',
    messagingSenderId: '611474656292',
    projectId: 'dishcovery-app-62ab5',
    databaseURL: 'https://dishcovery-app-62ab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dishcovery-app-62ab5.firebasestorage.app',
    iosClientId: '611474656292-0mrd908gq6o13pq0fd6ul49uu4g2hh3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.dishcoveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAImtyg3la371RZM26irYPETtuDygFX1Q0',
    appId: '1:611474656292:web:37eadbbacfed3804f25cb1',
    messagingSenderId: '611474656292',
    projectId: 'dishcovery-app-62ab5',
    authDomain: 'dishcovery-app-62ab5.firebaseapp.com',
    databaseURL: 'https://dishcovery-app-62ab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dishcovery-app-62ab5.firebasestorage.app',
    measurementId: 'G-3TLY92YZRC',
  );
}
