import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:dishcovery_app/models/restaurant_details_model.dart';
import 'package:dishcovery_app/services/restaurant_service.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:dishcovery_app/screen/map_picker_screen.dart';
import 'package:dishcovery_app/screen/add_restaurant_detail_screen.dart';
import 'package:dishcovery_app/constants/app_constants.dart';

class AddRestaurantScreen extends StatefulWidget {
  const AddRestaurantScreen({super.key});

  @override
  State<AddRestaurantScreen> createState() => _AddRestaurantScreenState();
}

class _AddRestaurantScreenState extends State<AddRestaurantScreen> {
  final _formKey = GlobalKey<FormState>();

  String _name = '';
  String _description = '';
  String _imageUrl = '';
  int _priceRange = 1;
  List<String> _selectedCuisines = [];
  String _phone = '';
  String _address = '';
  Map<String, dynamic> _openingHours = {};
  LatLng _location = const LatLng(13.736717, 100.523186);
  String _locationName = 'กรุณาเลือกตำแหน่ง';

  bool _isLoading = false;

  final List<Map<String, dynamic>> _foodOptions = [
    {'name': 'อาหารไทย', 'icon': Icons.ramen_dining_rounded},
    {'name': 'อาหารอีสาน', 'icon': Icons.local_fire_department_rounded},
    {'name': 'อาหารเหนือ', 'icon': Icons.terrain_rounded},
    {'name': 'อาหารใต้', 'icon': Icons.waves_rounded},
    {'name': 'อาหารญี่ปุ่น', 'icon': Icons.rice_bowl_rounded},
    {'name': 'อาหารเกาหลี', 'icon': Icons.restaurant_rounded},
    {'name': 'อาหารจีน', 'icon': Icons.set_meal_rounded},
    {'name': 'อาหารตะวันตก', 'icon': Icons.dinner_dining_rounded},
    {'name': 'ฟาสต์ฟู้ด', 'icon': Icons.fastfood_rounded},
    {'name': 'เบอร์เกอร์', 'icon': Icons.lunch_dining_rounded},
    {'name': 'พิซซ่า', 'icon': Icons.local_pizza_rounded},
    {'name': 'ไก่ทอด', 'icon': Icons.restaurant_menu_rounded},
    {'name': 'ก๋วยเตี๋ยว', 'icon': Icons.ramen_dining},
    {'name': 'ข้าวแกง', 'icon': Icons.rice_bowl},
    {'name': 'ข้าวมันไก่', 'icon': Icons.set_meal},
    {'name': 'อาหารตามสั่ง', 'icon': Icons.restaurant},
    {'name': 'ส้มตำ ไก่ย่าง', 'icon': Icons.food_bank},
    {'name': 'ปิ้งย่าง', 'icon': Icons.outdoor_grill_rounded},
    {'name': 'ชาบู / สุกี้', 'icon': Icons.soup_kitchen_rounded},
    {'name': 'เบเกอรี่', 'icon': Icons.cake_rounded},
    {'name': 'ของหวาน', 'icon': Icons.icecream_rounded},
    {'name': 'ไอศกรีม', 'icon': Icons.icecream},
    {'name': 'เครป', 'icon': Icons.egg},
    {'name': 'กาแฟ', 'icon': Icons.local_cafe_rounded},
    {'name': 'ชา / ชานม', 'icon': Icons.emoji_food_beverage_rounded},
    {'name': 'เครื่องดื่ม', 'icon': Icons.local_drink_rounded},
    {'name': 'อาหารเพื่อสุขภาพ', 'icon': Icons.eco_rounded},
    {'name': 'มังสวิรัติ', 'icon': Icons.grass_rounded},
    {'name': 'คลีน', 'icon': Icons.spa_rounded},
  ];

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();

    if (_selectedCuisines.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('กรุณาเลือกประเภทอาหารอย่างน้อย 1 อย่าง')),
      );
      return;
    }

    if (_locationName == 'กรุณาเลือกตำแหน่ง' ||
        _location == const LatLng(13.736717, 100.523186)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('กรุณาปักหมุดแผนที่ตำแหน่งร้านอาหาร')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // Map _openingHours to format required by TimeUtils
      Map<String, dynamic> formattedHours = {};
      final List<String> days = [
        'mon',
        'tue',
        'wed',
        'thu',
        'fri',
        'sat',
        'sun',
      ];
      for (var day in days) {
        if (_openingHours[day] != null && _openingHours[day] is Map) {
          if (_openingHours[day]['isClosed'] == true) {
            formattedHours[day] = [];
          } else {
            formattedHours[day] = [
              {
                'open': _openingHours[day]['open'],
                'close': _openingHours[day]['close'],
              },
            ];
          }
        } else if (_openingHours[day] is List) {
          formattedHours[day] = _openingHours[day];
        } else {
          formattedHours[day] = [];
        }
      }

      final newRestaurant = RestaurantDetailsData(
        id: '', // Will be generated by Firestore
        name: _name,
        cuisine: _selectedCuisines,
        priceRange: _priceRange,
        rating: 0.0,
        latitude: _location.latitude,
        longitude: _location.longitude,
        imageUrl: _imageUrl.isEmpty
            ? 'https://via.placeholder.com/400x300?text=No+Image'
            : _imageUrl,
        description: _description,
        address: _address,
        phone: _phone,
        openingHours: formattedHours,
      );

      if (mounted) {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) =>
                AddRestaurantDetailScreen(initialData: newRestaurant),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('เกิดข้อผิดพลาด: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  void _showTimePicker3Wheels() {
    final List<String> dayOptions = [
      'ทุกวัน',
      'เสาร์ - อาทิตย์',
      'จันทร์',
      'อังคาร',
      'พุธ',
      'พฤหัสบดี',
      'ศุกร์',
      'เสาร์',
      'อาทิตย์',
    ];

    List<String> times = [];
    for (int h = 0; h < 24; h++) {
      times.add('${h.toString().padLeft(2, '0')}:00');
      times.add('${h.toString().padLeft(2, '0')}:30');
    }

    int selectedDayIdx = 0;
    int selectedOpenIdx = 18; // 09:00
    int selectedCloseIdx = 40; // 20:00

    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return Container(
          height: 350,
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: Text(
                      'ยกเลิก',
                      style: AppTextStyles.signinText.copyWith(
                        color: Colors.grey,
                      ),
                    ),
                  ),
                  TextButton(
                    onPressed: () {
                      final selDay = dayOptions[selectedDayIdx];
                      final selOpen = times[selectedOpenIdx];
                      final selClose = times[selectedCloseIdx];

                      List<String> daysToUpdate = [];
                      if (selDay == 'ทุกวัน') {
                        daysToUpdate = [
                          'mon',
                          'tue',
                          'wed',
                          'thu',
                          'fri',
                          'sat',
                          'sun',
                        ];
                      } else if (selDay == 'เสาร์ - อาทิตย์') {
                        daysToUpdate = ['sat', 'sun'];
                      } else if (selDay == 'จันทร์') {
                        daysToUpdate = ['mon'];
                      } else if (selDay == 'อังคาร') {
                        daysToUpdate = ['tue'];
                      } else if (selDay == 'พุธ') {
                        daysToUpdate = ['wed'];
                      } else if (selDay == 'พฤหัสบดี') {
                        daysToUpdate = ['thu'];
                      } else if (selDay == 'ศุกร์') {
                        daysToUpdate = ['fri'];
                      } else if (selDay == 'เสาร์') {
                        daysToUpdate = ['sat'];
                      } else if (selDay == 'อาทิตย์') {
                        daysToUpdate = ['sun'];
                      }

                      setState(() {
                        for (var d in daysToUpdate) {
                          _openingHours[d] = [
                            {'open': selOpen, 'close': selClose},
                          ];
                        }
                      });
                      Navigator.pop(context);
                    },
                    child: Text(
                      'เพิ่ม',
                      style: AppTextStyles.signinText.copyWith(
                        color: AppColors.primaryBlue,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                ],
              ),
              Expanded(
                child: Row(
                  children: [
                    Expanded(
                      flex: 2,
                      child: CupertinoPicker(
                        scrollController: FixedExtentScrollController(
                          initialItem: selectedDayIdx,
                        ),
                        itemExtent: 40,
                        onSelectedItemChanged: (idx) => selectedDayIdx = idx,
                        children: dayOptions
                            .map(
                              (d) => Center(
                                child: Text(
                                  d,
                                  style: AppTextStyles.signinText.copyWith(
                                    fontSize: 16,
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    ),
                    Expanded(
                      flex: 1,
                      child: CupertinoPicker(
                        scrollController: FixedExtentScrollController(
                          initialItem: selectedOpenIdx,
                        ),
                        itemExtent: 40,
                        onSelectedItemChanged: (idx) => selectedOpenIdx = idx,
                        children: times
                            .map(
                              (t) => Center(
                                child: Text(
                                  t,
                                  style: AppTextStyles.signinText.copyWith(
                                    fontSize: 16,
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    ),
                    const Center(
                      child: Text(
                        ' - ',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                    Expanded(
                      flex: 1,
                      child: CupertinoPicker(
                        scrollController: FixedExtentScrollController(
                          initialItem: selectedCloseIdx,
                        ),
                        itemExtent: 40,
                        onSelectedItemChanged: (idx) => selectedCloseIdx = idx,
                        children: times
                            .map(
                              (t) => Center(
                                child: Text(
                                  t,
                                  style: AppTextStyles.signinText.copyWith(
                                    fontSize: 16,
                                  ),
                                ),
                              ),
                            )
                            .toList(),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  void _openCuisinePicker() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            return Padding(
              padding: EdgeInsets.only(
                bottom: MediaQuery.of(context).viewInsets.bottom,
              ),
              child: Container(
                height: MediaQuery.of(context).size.height * 0.9,
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Text(
                      'เลือกประเภทอาหาร',
                      style: AppTextStyles.signinText.copyWith(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Expanded(
                      child: SingleChildScrollView(
                        child: Wrap(
                          spacing: 10,
                          runSpacing: 10,
                          children: _foodOptions.map((option) {
                            final String name = option['name'];
                            final IconData icon = option['icon'];
                            final bool isSelected = _selectedCuisines.contains(
                              name,
                            );

                            return ChoiceChip(
                              showCheckmark: false,
                              label: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(icon, size: 18),
                                  const SizedBox(width: 4),
                                  Text(
                                    name,
                                    style: AppTextStyles.signinText.copyWith(
                                      color: AppColors.black,
                                      fontSize: 16,
                                    ),
                                  ),
                                ],
                              ),
                              selected: isSelected,
                              selectedColor: AppColors.lightBlue,
                              backgroundColor: AppColors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(24),
                                side: BorderSide(
                                  color: isSelected
                                      ? AppColors.primaryBlue
                                      : AppColors.black,
                                ),
                              ),
                              onSelected: (_) {
                                setModalState(() {
                                  if (isSelected) {
                                    _selectedCuisines.remove(name);
                                  } else {
                                    _selectedCuisines.add(name);
                                  }
                                });
                                setState(() {});
                              },
                            );
                          }).toList(),
                        ),
                      ),
                    ),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          child: TextButton(
                            onPressed: () => Navigator.pop(context),
                            style: TextButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 14),
                            ),
                            child: Text(
                              'ยกเลิก',
                              style: AppTextStyles.profileText.copyWith(
                                color: Colors.grey,
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: ElevatedButton(
                            onPressed: () => Navigator.pop(context),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primaryBlue,
                              padding: const EdgeInsets.symmetric(vertical: 14),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: Text(
                              'ตกลง',
                              style: AppTextStyles.profileText.copyWith(
                                color: Colors.white,
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  Future<void> _pickLocation() async {
    final result = await Navigator.push<Map<String, dynamic>>(
      context,
      MaterialPageRoute(
        builder: (context) => MapPickerScreen(initialLocation: _location),
      ),
    );

    if (result != null) {
      setState(() {
        _location = result['location'] as LatLng;
        _locationName = result['address'] as String;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text(
            'เพิ่มร้านอาหาร',
            style: AppTextStyles.signinText.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          backgroundColor: Colors.white,
          foregroundColor: Colors.black,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios_new),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        body: _isLoading
            ? const Center(child: CircularProgressIndicator())
            : SingleChildScrollView(
                padding: const EdgeInsets.all(20.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // 1. ชื่อร้านอาหาร
                      Text(
                        'ชื่อร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'กรอกชื่อร้าน',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกชื่อร้าน' : null,
                        onSaved: (v) => _name = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 2. คำอธิบายร้านอาหาร
                      Text(
                        'คำอธิบายร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'รายละเอียด หรือ ข้อมูลเพิ่มเติม',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        maxLines: 3,
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกคำอธิบาย' : null,
                        onSaved: (v) => _description = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 3. หมวดหมู่อาหาร
                      Text(
                        'หมวดหมู่ประเภทอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      GestureDetector(
                        onTap: _openCuisinePicker,
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 16,
                            vertical: 14,
                          ),
                          decoration: BoxDecoration(
                            color: Colors.grey.shade50,
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: Colors.grey.shade300),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: Text(
                                  _selectedCuisines.isEmpty
                                      ? 'เลือกหมวดหมู่อาหาร'
                                      : _selectedCuisines.join(', '),
                                  style: AppTextStyles.hintText.copyWith(
                                    color: _selectedCuisines.isEmpty
                                        ? Colors.grey
                                        : Colors.black,
                                  ),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              const Icon(Icons.arrow_drop_down),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),

                      // 4. เรทราคา
                      Text(
                        'เรทราคาของร้าน',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Row(
                          children: [1, 2, 3, 4].map((range) {
                            final isSelected = _priceRange == range;
                            final labels = [
                              '฿ ถูกกว่า 100',
                              '฿฿ 100-250',
                              '฿฿฿ 250-500',
                              '฿฿฿฿ 500+',
                            ];
                            return Padding(
                              padding: const EdgeInsets.only(right: 8.0),
                              child: ChoiceChip(
                                showCheckmark: false,
                                label: Text(
                                  labels[range - 1],
                                  style: AppTextStyles.hintText.copyWith(
                                    color: Colors.black,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                selected: isSelected,
                                selectedColor: AppColors.lightBlue,
                                backgroundColor: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(24),
                                  side: BorderSide(
                                    color: isSelected
                                        ? AppColors.primaryBlue
                                        : Colors.grey.shade300,
                                  ),
                                ),
                                onSelected: (_) =>
                                    setState(() => _priceRange = range),
                              ),
                            );
                          }).toList(),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        'เวลาเปิด-ปิดร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      // List of current configured hours
                      if (() {
                        bool hasOpen = false;
                        for (var v in _openingHours.values) {
                          if (v is List && v.isNotEmpty) hasOpen = true;
                        }
                        return hasOpen;
                      }())
                        Container(
                          margin: const EdgeInsets.only(bottom: 12),
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey.shade300),
                            borderRadius: BorderRadius.circular(12),
                          ),
                          child: Column(
                            children: () {
                              final List<String> daysKeys = [
                                'mon',
                                'tue',
                                'wed',
                                'thu',
                                'fri',
                                'sat',
                                'sun',
                              ];
                              final List<String> thDays = [
                                'จันทร์',
                                'อังคาร',
                                'พุธ',
                                'พฤหัสบดี',
                                'ศุกร์',
                                'เสาร์',
                                'อาทิตย์',
                              ];

                              List<Widget> rows = [];
                              for (int i = 0; i < daysKeys.length; i++) {
                                final d = daysKeys[i];
                                final val = _openingHours[d];
                                if (val != null &&
                                    val is List &&
                                    val.isNotEmpty) {
                                  rows.add(
                                    ListTile(
                                      title: Text(
                                        thDays[i],
                                        style: AppTextStyles.profileText
                                            .copyWith(
                                              fontSize: 14,
                                              color: Colors.grey[800],
                                            ),
                                      ),
                                      trailing: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          Text(
                                            '${val.first['open']} - ${val.first['close']}',
                                            style: AppTextStyles.profileText
                                                .copyWith(
                                                  fontSize: 14,
                                                  color: Colors.grey[800],
                                                ),
                                          ),
                                          IconButton(
                                            alignment: Alignment.centerRight,
                                            icon: const Icon(
                                              Icons.close,
                                              color: Colors.red,
                                              size: 16,
                                            ),
                                            onPressed: () {
                                              setState(() {
                                                _openingHours.remove(d);
                                              });
                                            },
                                          ),
                                        ],
                                      ),
                                    ),
                                  );
                                  rows.add(
                                    const Divider(
                                      height: 1,
                                      indent: 16,
                                      endIndent: 16,
                                    ),
                                  );
                                }
                              }
                              if (rows.isNotEmpty)
                                rows.removeLast(); // remove trailng divider
                              return rows;
                            }(),
                          ),
                        ),
                      ElevatedButton.icon(
                        onPressed: _showTimePicker3Wheels,
                        icon: const Icon(Icons.add, color: Colors.white),
                        label: Text(
                          'เพิ่ม',
                          style: AppTextStyles.hintText.copyWith(
                            color: Colors.white,
                          ),
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primaryBlue,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),

                      // 5. เบอร์โทรศัพท์
                      Text(
                        'เบอร์ติดต่อ',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        maxLength: 10,
                        keyboardType: TextInputType.phone,
                        inputFormatters: [
                          FilteringTextInputFormatter.digitsOnly,
                        ],
                        decoration: InputDecoration(
                          hintText: '0xxxxxxxxx',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          counterText: "",
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        validator: (v) => v == null || v.isEmpty
                            ? 'กรุณากรอกเบอร์ติดต่อ'
                            : null,
                        onSaved: (v) => _phone = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 6. ที่อยู่
                      Text(
                        'ที่อยู่ของร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'ที่อยู่อย่างละเอียด',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        maxLines: 2,
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกที่อยู่' : null,
                        onSaved: (v) => _address = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 8. พิกัดแผนที่
                      Text(
                        'พิกัดแผนที่',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Expanded(
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 16,
                                vertical: 14,
                              ),
                              decoration: BoxDecoration(
                                color: Colors.grey.shade100,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: Colors.grey.shade300),
                              ),
                              child: Text(
                                _locationName.isEmpty
                                    ? '${_location.latitude.toStringAsFixed(4)}, ${_location.longitude.toStringAsFixed(4)}'
                                    : _locationName,
                                style: AppTextStyles.hintText.copyWith(),
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                          ),
                          const SizedBox(width: 10),
                          ElevatedButton.icon(
                            onPressed: _pickLocation,
                            icon: const Icon(Icons.map, color: Colors.white),
                            label: Text(
                              'ตั้งค่าพิกัด',
                              style: AppTextStyles.hintText.copyWith(
                                color: Colors.white,
                              ),
                            ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primaryBlue,
                              padding: const EdgeInsets.all(14),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 20),

                      const SizedBox(height: 40),
                      SizedBox(
                        height: 55,
                        child: ElevatedButton(
                          onPressed: _submit,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF001738),
                            foregroundColor: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(30),
                            ),
                            elevation: 5,
                          ),
                          child: Text(
                            'หน้าต่อไป',
                            style: AppTextStyles.profileText.copyWith(
                              color: Colors.white,
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                    ],
                  ),
                ),
              ),
      ),
    );
  }
}
