import 'package:flutter/material.dart';
import 'package:dishcovery_app/models/restaurant_details_model.dart';
import 'package:dishcovery_app/services/restaurant_service.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:dishcovery_app/screen/map_picker_screen.dart';
import 'package:dishcovery_app/screen/add_restaurant_detail_screen.dart';
import 'package:dishcovery_app/constants/app_constants.dart';

class AddRestaurantScreen extends StatefulWidget {
  const AddRestaurantScreen({super.key});

  @override
  State<AddRestaurantScreen> createState() => _AddRestaurantScreenState();
}

class _AddRestaurantScreenState extends State<AddRestaurantScreen> {
  final _formKey = GlobalKey<FormState>();

  String _name = '';
  String _description = '';
  String _imageUrl = '';
  int _priceRange = 1;
  List<String> _selectedCuisines = [];
  String _phone = '';
  String _address = '';
  Map<String, dynamic> _openingHours = {};
  LatLng _location = const LatLng(13.736717, 100.523186);
  String _locationName = 'กรุณาเลือกตำแหน่ง';

  bool _isLoading = false;

  final List<Map<String, dynamic>> _foodOptions = [
    {'name': 'อาหารไทย', 'icon': Icons.ramen_dining_rounded},
    {'name': 'อาหารอีสาน', 'icon': Icons.local_fire_department_rounded},
    {'name': 'อาหารเหนือ', 'icon': Icons.terrain_rounded},
    {'name': 'อาหารใต้', 'icon': Icons.waves_rounded},
    {'name': 'อาหารญี่ปุ่น', 'icon': Icons.rice_bowl_rounded},
    {'name': 'อาหารเกาหลี', 'icon': Icons.restaurant_rounded},
    {'name': 'อาหารจีน', 'icon': Icons.set_meal_rounded},
    {'name': 'อาหารตะวันตก', 'icon': Icons.dinner_dining_rounded},
    {'name': 'ฟาสต์ฟู้ด', 'icon': Icons.fastfood_rounded},
    {'name': 'เบอร์เกอร์', 'icon': Icons.lunch_dining_rounded},
    {'name': 'พิซซ่า', 'icon': Icons.local_pizza_rounded},
    {'name': 'ไก่ทอด', 'icon': Icons.restaurant_menu_rounded},
    {'name': 'ก๋วยเตี๋ยว', 'icon': Icons.ramen_dining},
    {'name': 'ข้าวแกง', 'icon': Icons.rice_bowl},
    {'name': 'ข้าวมันไก่', 'icon': Icons.set_meal},
    {'name': 'อาหารตามสั่ง', 'icon': Icons.restaurant},
    {'name': 'ส้มตำ ไก่ย่าง', 'icon': Icons.food_bank},
    {'name': 'ปิ้งย่าง', 'icon': Icons.outdoor_grill_rounded},
    {'name': 'ชาบู / สุกี้', 'icon': Icons.soup_kitchen_rounded},
    {'name': 'เบเกอรี่', 'icon': Icons.cake_rounded},
    {'name': 'ของหวาน', 'icon': Icons.icecream_rounded},
    {'name': 'ไอศกรีม', 'icon': Icons.icecream},
    {'name': 'เครป', 'icon': Icons.egg},
    {'name': 'กาแฟ', 'icon': Icons.local_cafe_rounded},
    {'name': 'ชา / ชานม', 'icon': Icons.emoji_food_beverage_rounded},
    {'name': 'เครื่องดื่ม', 'icon': Icons.local_drink_rounded},
    {'name': 'อาหารเพื่อสุขภาพ', 'icon': Icons.eco_rounded},
    {'name': 'มังสวิรัติ', 'icon': Icons.grass_rounded},
    {'name': 'คลีน', 'icon': Icons.spa_rounded},
  ];

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();

    if (_selectedCuisines.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('กรุณาเลือกประเภทอาหารอย่างน้อย 1 อย่าง')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    try {
      // Map _openingHours to format required by TimeUtils
      Map<String, dynamic> formattedHours = {};
      final List<String> days = [
        'mon',
        'tue',
        'wed',
        'thu',
        'fri',
        'sat',
        'sun',
      ];
      for (var day in days) {
        if (_openingHours[day] != null && _openingHours[day] is Map) {
          if (_openingHours[day]['isClosed'] == true) {
            formattedHours[day] = [];
          } else {
            formattedHours[day] = [
              {
                'open': _openingHours[day]['open'],
                'close': _openingHours[day]['close'],
              },
            ];
          }
        } else if (_openingHours[day] is List) {
          formattedHours[day] = _openingHours[day];
        } else {
          formattedHours[day] = [];
        }
      }

      final newRestaurant = RestaurantDetailsData(
        id: '', // Will be generated by Firestore
        name: _name,
        cuisine: _selectedCuisines,
        priceRange: _priceRange,
        rating: 0.0,
        latitude: _location.latitude,
        longitude: _location.longitude,
        imageUrl: _imageUrl.isEmpty
            ? 'https://via.placeholder.com/400x300?text=No+Image'
            : _imageUrl,
        description: _description,
        address: _address,
        phone: _phone,
        openingHours: formattedHours,
      );

      if (mounted) {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) =>
                AddRestaurantDetailScreen(initialData: newRestaurant),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('เกิดข้อผิดพลาด: $e')));
      }
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  void _openHoursPicker() {
    final List<String> days = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
    final List<String> thDays = [
      'จันทร์',
      'อังคาร',
      'พุธ',
      'พฤหัสบดี',
      'ศุกร์',
      'เสาร์',
      'อาทิตย์',
    ];

    // Initialize defaults if empty
    if (_openingHours.isEmpty) {
      for (var day in days) {
        _openingHours[day] = {
          'open': '09:00',
          'close': '20:00',
          'isClosed': false,
        };
      }
    }

    // copy to local state for modal
    Map<String, dynamic> tempHours = Map<String, dynamic>.from(
      _openingHours.map((k, v) {
        if (v is List) {
          // Backwards compatibility from formatted structure
          if (v.isEmpty)
            return MapEntry(k, {
              'open': '09:00',
              'close': '20:00',
              'isClosed': true,
            });
          return MapEntry(k, {
            'open': v.first['open'],
            'close': v.first['close'],
            'isClosed': false,
          });
        }
        return MapEntry(k, Map<String, dynamic>.from(v));
      }),
    );

    Future<TimeOfDay?> _selectTime(
      BuildContext context,
      String currentStr,
    ) async {
      final timeParts = currentStr.split(':');
      final current = TimeOfDay(
        hour: int.parse(timeParts[0]),
        minute: int.parse(timeParts[1]),
      );
      return await showTimePicker(context: context, initialTime: current);
    }

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            return Container(
              height: MediaQuery.of(context).size.height * 0.8,
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text(
                    'ตั้งเวลาเปิด-ปิดร้าน',
                    style: AppTextStyles.signinText.copyWith(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 32),
                  Expanded(
                    child: ListView.builder(
                      itemCount: days.length,
                      itemBuilder: (context, index) {
                        String day = days[index];
                        String thDay = thDays[index];
                        bool isClosed = tempHours[day]['isClosed'];
                        return Column(
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                SizedBox(
                                  width: 70,
                                  child: Text(
                                    thDay,
                                    style: AppTextStyles.hintText.copyWith(
                                      color: Colors.black87,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                                Switch(
                                  value: !isClosed,
                                  onChanged: (val) => setModalState(
                                    () => tempHours[day]['isClosed'] = !val,
                                  ),
                                ),
                                if (!isClosed)
                                  Row(
                                    children: [
                                      TextButton(
                                        onPressed: () async {
                                          final picked = await _selectTime(
                                            context,
                                            tempHours[day]['open'],
                                          );
                                          if (picked != null) {
                                            setModalState(
                                              () => tempHours[day]['open'] =
                                                  '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}',
                                            );
                                          }
                                        },
                                        child: Text(tempHours[day]['open']),
                                      ),
                                      const Text('-'),
                                      TextButton(
                                        onPressed: () async {
                                          final picked = await _selectTime(
                                            context,
                                            tempHours[day]['close'],
                                          );
                                          if (picked != null) {
                                            setModalState(
                                              () => tempHours[day]['close'] =
                                                  '${picked.hour.toString().padLeft(2, '0')}:${picked.minute.toString().padLeft(2, '0')}',
                                            );
                                          }
                                        },
                                        child: Text(tempHours[day]['close']),
                                      ),
                                    ],
                                  )
                                else
                                  Text(
                                    ' ปิดทำการ',
                                    style: AppTextStyles.hintText.copyWith(
                                      color: Colors.red,
                                    ),
                                  ),
                              ],
                            ),
                            const Divider(),
                          ],
                        );
                      },
                    ),
                  ),
                  ElevatedButton(
                    onPressed: () {
                      setState(() {
                        // Convert tempHours to the exact format needed by TimeUtils
                        Map<String, dynamic> formattedHours = {};
                        for (var day in days) {
                          if (tempHours[day]['isClosed']) {
                            formattedHours[day] = []; // Empty list means closed
                          } else {
                            formattedHours[day] = [
                              {
                                'open': tempHours[day]['open'],
                                'close': tempHours[day]['close'],
                              },
                            ];
                          }
                        }
                        _openingHours =
                            formattedHours; // Update _openingHours with the formatted data
                      });
                      Navigator.pop(context);
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.black,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(25),
                      ),
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                    child: Text(
                      'บันทึกเวลา',
                      style: AppTextStyles.signinText.copyWith(
                        color: Colors.white,
                        fontSize: 18,
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  void _openCuisinePicker() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.white,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            return Container(
              height: MediaQuery.of(context).size.height * 0.8,
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'เลือกประเภทอาหาร',
                    style: AppTextStyles.signinText.copyWith(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 16),
                  Expanded(
                    child: SingleChildScrollView(
                      child: Wrap(
                        spacing: 10,
                        runSpacing: 10,
                        children: _foodOptions.map((option) {
                          final String name = option['name'];
                          final IconData icon = option['icon'];
                          final bool isSelected = _selectedCuisines.contains(
                            name,
                          );

                          return ChoiceChip(
                            showCheckmark: false,
                            label: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(icon, size: 18),
                                const SizedBox(width: 4),
                                Text(
                                  name,
                                  style: AppTextStyles.signinText.copyWith(
                                    color: AppColors.black,
                                    fontSize: 16,
                                  ),
                                ),
                              ],
                            ),
                            selected: isSelected,
                            selectedColor: AppColors.lightBlue,
                            backgroundColor: AppColors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(24),
                              side: BorderSide(
                                color: isSelected
                                    ? AppColors.primaryBlue
                                    : AppColors.black,
                              ),
                            ),
                            onSelected: (_) {
                              setModalState(() {
                                if (isSelected) {
                                  _selectedCuisines.remove(name);
                                } else {
                                  _selectedCuisines.add(name);
                                }
                              });
                              setState(() {});
                            },
                          );
                        }).toList(),
                      ),
                    ),
                  ),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton(
                      onPressed: () => Navigator.pop(context),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.black,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(25),
                        ),
                      ),
                      child: Text(
                        'ตกลง',
                        style: AppTextStyles.signinText.copyWith(
                          color: Colors.white,
                          fontSize: 18,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  Future<void> _pickLocation() async {
    final result = await Navigator.push<Map<String, dynamic>>(
      context,
      MaterialPageRoute(
        builder: (context) => MapPickerScreen(initialLocation: _location),
      ),
    );

    if (result != null) {
      setState(() {
        _location = result['location'] as LatLng;
        _locationName = result['address'] as String;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: Text(
            'เพิ่มร้านอาหาร',
            style: AppTextStyles.signinText.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          backgroundColor: Colors.white,
          foregroundColor: Colors.black,
          elevation: 0,
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios_new),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        body: _isLoading
            ? const Center(child: CircularProgressIndicator())
            : SingleChildScrollView(
                padding: const EdgeInsets.all(20.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // 1. ชื่อร้านอาหาร
                      Text(
                        'ชื่อร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'กรอกชื่อร้าน',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกชื่อร้าน' : null,
                        onSaved: (v) => _name = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 2. คำอธิบายร้านอาหาร
                      Text(
                        'คำอธิบายร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'รายละเอียด หรือ ข้อมูลเพิ่มเติม',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        maxLines: 3,
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกคำอธิบาย' : null,
                        onSaved: (v) => _description = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 3. หมวดหมู่อาหาร
                      Text(
                        'หมวดหมู่ประเภทอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      GestureDetector(
                        onTap: _openCuisinePicker,
                        child: Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 16,
                            vertical: 14,
                          ),
                          decoration: BoxDecoration(
                            color: Colors.grey.shade50,
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: Colors.grey.shade300),
                          ),
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: Text(
                                  _selectedCuisines.isEmpty
                                      ? 'เลือกหมวดหมู่อาหาร'
                                      : _selectedCuisines.join(', '),
                                  style: AppTextStyles.hintText.copyWith(
                                    color: _selectedCuisines.isEmpty
                                        ? Colors.grey
                                        : Colors.black,
                                  ),
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              const Icon(Icons.arrow_drop_down),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),

                      // 4. เรทราคา
                      Text(
                        'เรทราคาของร้าน',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Row(
                          children: [1, 2, 3, 4].map((range) {
                            final isSelected = _priceRange == range;
                            final labels = [
                              '฿ ถูกกว่า 100',
                              '฿฿ 100-250',
                              '฿฿฿ 250-500',
                              '฿฿฿฿ 500+',
                            ];
                            return Padding(
                              padding: const EdgeInsets.only(right: 8.0),
                              child: ChoiceChip(
                                showCheckmark: false,
                                label: Text(
                                  labels[range - 1],
                                  style: AppTextStyles.hintText.copyWith(
                                    color: Colors.black,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                selected: isSelected,
                                selectedColor: AppColors.lightBlue,
                                backgroundColor: Colors.white,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(24),
                                  side: BorderSide(
                                    color: isSelected
                                        ? AppColors.primaryBlue
                                        : Colors.grey.shade300,
                                  ),
                                ),
                                onSelected: (_) =>
                                    setState(() => _priceRange = range),
                              ),
                            );
                          }).toList(),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        'เวลาเปิด-ปิดร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      ElevatedButton.icon(
                        onPressed: _openHoursPicker,
                        icon: const Icon(
                          Icons.access_time,
                          color: Colors.white,
                        ),
                        label: Text(
                          _openingHours.isEmpty
                              ? 'ตั้งค่าเวลาเปิด-ปิด'
                              : 'ตั้งค่าแล้ว (แก้ไข)',
                          style: AppTextStyles.hintText.copyWith(
                            color: Colors.white,
                          ),
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primaryBlue,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),

                      // 5. เบอร์โทรศัพท์
                      Text(
                        'เบอร์ติดต่อ',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        maxLength: 10,

                        keyboardType: TextInputType.phone,
                        decoration: InputDecoration(
                          hintText: '0xxxxxxxxx',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          counterText: "",
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        validator: (v) => v == null || v.isEmpty
                            ? 'กรุณากรอกเบอร์ติดต่อ'
                            : null,
                        onSaved: (v) => _phone = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 6. ที่อยู่
                      Text(
                        'ที่อยู่ของร้านอาหาร',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      TextFormField(
                        decoration: InputDecoration(
                          hintText: 'ที่อยู่อย่างละเอียด',
                          hintStyle: AppTextStyles.hintText.copyWith(),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(12),
                            borderSide: BorderSide(color: Colors.grey.shade300),
                          ),
                          filled: true,
                          fillColor: Colors.grey.shade50,
                        ),
                        maxLines: 2,
                        validator: (v) =>
                            v == null || v.isEmpty ? 'กรุณากรอกที่อยู่' : null,
                        onSaved: (v) => _address = v ?? '',
                      ),
                      const SizedBox(height: 20),

                      // 8. พิกัดแผนที่
                      Text(
                        'พิกัดแผนที่',
                        style: AppTextStyles.signinText.copyWith(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Expanded(
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 16,
                                vertical: 14,
                              ),
                              decoration: BoxDecoration(
                                color: Colors.grey.shade100,
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: Colors.grey.shade300),
                              ),
                              child: Text(
                                _locationName.isEmpty
                                    ? '${_location.latitude.toStringAsFixed(4)}, ${_location.longitude.toStringAsFixed(4)}'
                                    : _locationName,
                                style: AppTextStyles.hintText.copyWith(),
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                          ),
                          const SizedBox(width: 10),
                          ElevatedButton.icon(
                            onPressed: _pickLocation,
                            icon: const Icon(Icons.map, color: Colors.white),
                            label: Text(
                              'ตั้งค่าพิกัด',
                              style: AppTextStyles.hintText.copyWith(
                                color: Colors.white,
                              ),
                            ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.primaryBlue,
                              padding: const EdgeInsets.all(14),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 20),

                      const SizedBox(height: 40),
                      SizedBox(
                        height: 55,
                        child: ElevatedButton(
                          onPressed: _submit,
                          style: ElevatedButton.styleFrom(
                            backgroundColor: const Color(0xFF001738),
                            foregroundColor: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(30),
                            ),
                            elevation: 5,
                          ),
                          child: Text(
                            'หน้าต่อไป',
                            style: AppTextStyles.profileText.copyWith(
                              color: Colors.white,
                              fontSize: 18,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                    ],
                  ),
                ),
              ),
      ),
    );
  }
}
